# Generated by Django 5.2.15 on 2026-07-06 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Short abbreviation used in reference numbers, e.g. HR, FIN, LEG', max_length=10, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(blank=True, help_text='Auto-generated: AE/{DEPT}/{SEQ}/{YY}', max_length=30, unique=True)),
                ('direction', models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing')], max_length=10)),
                ('date', models.DateField(help_text='Date received or sent')),
                ('sender', models.CharField(blank=True, help_text='For incoming letters', max_length=200)),
                ('recipient', models.CharField(blank=True, help_text='For outgoing letters', max_length=200)),
                ('subject', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('LEGAL', 'Legal'), ('FINANCIAL', 'Financial'), ('CUSTOMER', 'Customer'), ('GOVERNMENT', 'Government'), ('INTERNAL', 'Internal'), ('HR', 'Human Resources'), ('VENDOR', 'Vendor'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('CONFIDENTIAL', 'Confidential')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('IN_REVIEW', 'In Review'), ('ACTIONED', 'Actioned'), ('RESPONDED', 'Responded'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='RECEIVED', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters', to='letters.department')),
                ('assigned_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_letters', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_letters', to=settings.AUTH_USER_MODEL)),
                ('related_letter', models.ForeignKey(blank=True, help_text='Link to original letter (for replies)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='letters.letter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='letters/attachments/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='letters.letter')),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='letters.letter')),
            ],
            options={
                'ordering': ['-action_date'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('last_number', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='letters.department')),
            ],
            options={
                'unique_together': {('department', 'year')},
            },
        ),
    ]
