# Generated by Django 5.2.15 on 2026-07-06 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_all_letters', 'Can view all letters across all departments')]},
        ),
        migrations.AddField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Staff members belonging to this department', related_name='departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
