# Generated by Django 5.2.15 on 2026-07-06 14:51

from django.db import migrations


def migrate_categories(apps, schema_editor):
    Category = apps.get_model('letters', 'Category')
    Letter = apps.get_model('letters', 'Letter')

    CATEGORY_CHOICES = [
        ('LEGAL', 'Legal'),
        ('FINANCIAL', 'Financial'),
        ('CUSTOMER', 'Customer'),
        ('GOVERNMENT', 'Government'),
        ('INTERNAL', 'Internal'),
        ('HR', 'Human Resources'),
        ('VENDOR', 'Vendor'),
        ('OTHER', 'Other'),
    ]

    # Create Categories
    category_objs = {}
    for code, name in CATEGORY_CHOICES:
        cat, _ = Category.objects.get_or_create(
            code=code,
            defaults={'name': name}
        )
        category_objs[code] = cat

    # Map letters to new category foreign keys
    for letter in Letter.objects.all():
        old_cat = letter.category
        if old_cat in category_objs:
            letter.category_fk = category_objs[old_cat]
            letter.save()


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_category_letter_category_fk'),
    ]

    operations = [
        migrations.RunPython(migrate_categories),
    ]
