# Generated by Django 5.2.15 on 2026-07-06 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_auto_20260706_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='category',
        ),
        migrations.RenameField(
            model_name='letter',
            old_name='category_fk',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='letter',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='letters',
                to='letters.category',
            ),
        ),
    ]
