# Generated by Django 5.2.15 on 2026-07-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0005_remove_letter_category_fk_alter_letter_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='letter_type',
            field=models.CharField(choices=[('HARDCOPY', 'Hardcopy'), ('DIGITAL', 'Digital')], default='DIGITAL', help_text='Format of the letter (Hardcopy or Digital)', max_length=10),
        ),
    ]
