# Generated by Django 5.2.15 on 2026-07-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0006_letter_letter_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_all_letters', 'Can view all letters across all departments'), ('can_view_outgoing_letters', 'Can view outgoing letters'), ('can_view_incoming_letters', 'Can view incoming letters')]},
        ),
    ]
