# Generated by Django 4.2.7 on 2026-07-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0008_userprofile_savedsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='reference_no',
            field=models.CharField(blank=True, help_text='For incoming letters: enter manually. For outgoing letters: auto-generated as AE/{DEPT}/{SEQ}/{YY}', max_length=50, unique=True),
        ),
    ]
