# Generated by Django 4.2.7 on 2026-07-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0009_alter_letter_reference_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='status',
            field=models.CharField(choices=[('DRAFTED', 'Drafted'), ('IN_REVIEW', 'In Review'), ('SUBMITTED', 'Submitted'), ('RESPONDED', 'Responded'), ('ARCHIVED', 'Archived')], default='DRAFTED', max_length=20),
        ),
    ]
