# Generated by Django 4.2.7 on 2026-07-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0010_alter_letter_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='remarks',
        ),
    ]
