# Generated by Django 4.2.7 on 2026-07-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0011_remove_letter_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('DRAFTED', 'Drafted'), ('IN_REVIEW', 'In Review'), ('ACTIONED', 'Actioned'), ('SUBMITTED', 'Submitted'), ('RESPONDED', 'Responded'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='DRAFTED', max_length=20),
        ),
    ]
