# Generated by Django 5.2.16 on 2026-07-09 15:03

import letters.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0012_alter_letter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=letters.storage.R2Storage(), upload_to='letters/attachments/%Y/%m/'),
        ),
    ]
