# Generated by Django 5.2.16 on 2026-07-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0013_attachment_short_code_alter_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='access_count',
            field=models.IntegerField(default=0, help_text='Number of times the shared link has been accessed'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='custom_short_code',
            field=models.CharField(blank=True, help_text='Custom short code for sharing (optional)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration date for the shared link (optional)', null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='last_accessed',
            field=models.DateTimeField(blank=True, help_text='Last time the shared link was accessed', null=True),
        ),
    ]
