# Generated by Django 5.2.16 on 2026-07-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0014_attachment_access_count_attachment_custom_short_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='letter_type',
            field=models.CharField(choices=[('HARDCOPY', 'Hardcopy'), ('DIGITAL', 'Digital')], default='HARDCOPY', help_text='Format of the letter (Hardcopy or Digital)', max_length=10),
        ),
    ]
