# Generated by Django 5.2.16 on 2026-07-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0015_alter_letter_letter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/%Y/%m/'),
        ),
    ]
