# Generated by Django 5.2.16 on 2026-07-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0018_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram chat ID for notifications', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_notifications',
            field=models.BooleanField(default=False, help_text='Receive Telegram notifications'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='letters/attachments/%Y/%m/'),
        ),
    ]
