# Generated by Django 5.2.16 on 2026-07-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0019_userprofile_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_connection_code',
            field=models.CharField(blank=True, help_text='Code for connecting Telegram account', max_length=20, null=True, unique=True),
        ),
    ]
