# Generated by Django 5.2.16 on 2026-07-14 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0020_userprofile_telegram_connection_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_connected_at',
            field=models.DateTimeField(blank=True, help_text='When Telegram account was connected', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_connection_code',
            field=models.CharField(blank=True, help_text='Code for connecting Telegram account (deprecated, use TelegramLinkToken)', max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Link Token',
                'verbose_name_plural': 'Telegram Link Tokens',
                'indexes': [models.Index(fields=['token'], name='letters_tel_token_135e89_idx'), models.Index(fields=['expires_at', 'is_used'], name='letters_tel_expires_72bdd3_idx')],
            },
        ),
    ]
