# Generated by Django 5.1.15 on 2026-08-04 08:42

import django.db.models.deletion
import letters.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0021_userprofile_telegram_connected_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=letters.storage.R2Storage(), upload_to='letters/attachments/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='AttachmentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Viewed'), ('download', 'Downloaded'), ('share', 'Shared')], default='view', max_length=10)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='letters.attachment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['attachment', 'user'], name='letters_att_attachm_f3d773_idx')],
            },
        ),
    ]
