# Generated by Django 5.1.15 on 2026-08-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0022_alter_attachment_file_attachmentview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachmentview',
            options={'ordering': ['-viewed_at'], 'permissions': [('can_view_attachment_analytics', 'Can view staff attachment interaction logs')]},
        ),
    ]
