# Generated by Django 5.1.15 on 2026-08-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0023_alter_attachmentview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='attention_to',
            field=models.CharField(blank=True, help_text='Attention to (specific person or office)', max_length=200),
        ),
    ]
