# Generated by Django 5.1.15 on 2026-08-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0024_letter_attention_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
